FROM nikolaik/python-nodejs:latest
WORKDIR /src
COPY requirements.txt .
RUN pip install -r requirements.txt \
    && pip install --pre --upgrade kubernetes \
    && npm install -g nodemon
CMD nodemon -e py -L --exec "kopf run app/startup.py app/injector.py --verbose --all-namespaces --liveness=http://0.0.0.0:8080/healthz"
ENV PYTHONPATH /src
COPY template template/
COPY share share/
COPY app app/